# Generated by Django 5.0.6 on 2024-11-18 18:49

import django.db.models.deletion
import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('cover_photo', models.ImageField(upload_to='articles_files/cover_photos')),
                ('datetime', models.DateField(auto_now=True)),
                ('slug', models.SlugField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Certificates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate', models.ImageField(upload_to=main.models.certificate_upload_path)),
            ],
            options={
                'verbose_name': 'Грамота',
                'verbose_name_plural': 'Грамоты',
            },
        ),
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=200, unique=True, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Полезная ссылка',
                'verbose_name_plural': 'Полезные ссылки',
            },
        ),
        migrations.CreateModel(
            name='MainPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=main.models.main_photo_upload_path)),
            ],
            options={
                'verbose_name': 'Основное фото',
                'verbose_name_plural': 'Основные фото',
            },
        ),
        migrations.CreateModel(
            name='MainText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=10000)),
            ],
            options={
                'verbose_name': 'Основной текст',
                'verbose_name_plural': 'Основные тексты',
            },
        ),
        migrations.CreateModel(
            name='ArticleFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='articles_files/photos')),
                ('article', models.ForeignKey(default='asdf', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='article_files', to='main.article')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='photos',
            field=models.ManyToManyField(related_name='article_photos', to='main.articlefiles'),
        ),
    ]
